#!/bin/bash

# Bedrock Express Mobile Build Script
# Builds the mobile app HTML and prepares it for Capacitor

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Determine environment
MOBILE_ENV=${MOBILE_ENV:-local}
print_info "Building for environment: $MOBILE_ENV"

# Allow URLs to be passed as environment variables
# Set these in your environment or .env file before building
PRODUCTION_URL=${PRODUCTION_URL:-"https://your-production-domain.com"}
STAGING_URL=${STAGING_URL:-"https://your-staging-domain.com"}
DEVELOPMENT_URL=${DEVELOPMENT_URL:-"https://your-development-domain.com"}
LOCAL_URL=${LOCAL_URL:-"http://localhost:8000"}

# Set API URLs based on environment
case $MOBILE_ENV in
    production)
        API_URL="$PRODUCTION_URL"
        APP_NAME="Bedrock Chat"
        print_info "Using production API: $API_URL"
        ;;
    staging)
        API_URL="$STAGING_URL"
        APP_NAME="Bedrock Chat (Staging)"
        print_info "Using staging API: $API_URL"
        ;;
    development)
        API_URL="$DEVELOPMENT_URL"
        APP_NAME="Bedrock Chat (Dev)"
        print_info "Using development API: $API_URL"
        ;;
    local|*)
        API_URL="$LOCAL_URL"
        print_info "Using local API: $API_URL"
        APP_NAME="Bedrock Chat (Local)"
        ;;
esac

# Create output directory
DIST_DIR="frontend/public/static/dist"
print_info "Creating dist directory: $DIST_DIR"
mkdir -p "$DIST_DIR"

# Build mobile HTML
if [ -f "mobile-chat-app.html" ]; then
    print_info "Processing mobile-chat-app.html..."

    # Create a temporary file for processing
    TEMP_FILE=$(mktemp)

    # Copy and process the HTML file
    cp mobile-chat-app.html "$TEMP_FILE"

    # Replace environment variables in the HTML
    # Use @ as delimiter for sed to handle URLs with slashes
    # Cross-platform sed -i (macOS requires '' argument, Linux doesn't)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s@window\.MOBILE_ENV || 'production'@'$MOBILE_ENV'@g" "$TEMP_FILE"
        sed -i '' "s@https://api\.example\.com@$API_URL@g" "$TEMP_FILE"
        sed -i '' "s@https://staging\.example\.com@$API_URL@g" "$TEMP_FILE"
        sed -i '' "s@http://localhost:8000@$API_URL@g" "$TEMP_FILE"
        sed -i '' "s@Bedrock Express Chat@$APP_NAME@g" "$TEMP_FILE"
    else
        sed -i "s@window\.MOBILE_ENV || 'production'@'$MOBILE_ENV'@g" "$TEMP_FILE"
        sed -i "s@https://api\.example\.com@$API_URL@g" "$TEMP_FILE"
        sed -i "s@https://staging\.example\.com@$API_URL@g" "$TEMP_FILE"
        sed -i "s@http://localhost:8000@$API_URL@g" "$TEMP_FILE"
        sed -i "s@Bedrock Express Chat@$APP_NAME@g" "$TEMP_FILE"
    fi

    # Copy processed file to dist
    cp "$TEMP_FILE" "$DIST_DIR/index.html"
    rm "$TEMP_FILE"

    print_success "Mobile HTML built and configured"
else
    print_error "mobile-chat-app.html not found!"
    exit 1
fi

# Create mobile configuration file
print_info "Creating mobile configuration..."
cat > "$DIST_DIR/mobile-config.js" << EOF
// Mobile App Configuration
// Auto-generated by build-mobile.sh

window.MOBILE_CONFIG = {
    environment: '$MOBILE_ENV',
    apiUrl: '$API_URL',
    appName: '$APP_NAME',
    version: '1.0.0',
    buildTime: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")',

    // All environment URLs (for easy switching)
    environments: {
        local: '$LOCAL_URL',
        development: '$DEVELOPMENT_URL',
        staging: '$STAGING_URL',
        production: '$PRODUCTION_URL'
    },

    // API endpoints
    endpoints: {
        auth: {
            google: '$API_URL/auth/google',
            callback: '$API_URL/auth/google/callback',
            status: '$API_URL/auth/status',
            logout: '$API_URL/auth/logout'
        },
        chat: {
            send: '$API_URL/api/chat/message',
            stream: '$API_URL/api/chat/stream',
            history: '$API_URL/conversation_history',
            conversation: '$API_URL/get_conversation',
            reset: '$API_URL/reset'
        }
    },

    // OAuth configuration
    oauth: {
        google: {
            redirectUri: '$API_URL/mobile/auth',
            scope: 'openid profile email'
        }
    },

    // Feature flags
    features: {
        offlineMode: false,
        pushNotifications: false,
        biometricAuth: false
    }
};

console.log('Mobile config loaded:', window.MOBILE_CONFIG);
EOF

print_success "Mobile configuration created"

# Create a simple manifest file
print_info "Creating manifest.json..."
cat > "$DIST_DIR/manifest.json" << EOF
{
    "name": "$APP_NAME",
    "short_name": "Bedrock Chat",
    "description": "AI-powered chat application",
    "start_url": "/",
    "display": "standalone",
    "background_color": "#f5f7fa",
    "theme_color": "#2c3e50",
    "icons": [
        {
            "src": "/icon-192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/icon-512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}
EOF

print_success "Manifest created"

# Create placeholder icons if they don't exist
if [ ! -f "$DIST_DIR/icon-192.png" ]; then
    print_warning "Icons not found, creating placeholders..."

    # Create a simple SVG icon
    cat > "$DIST_DIR/icon.svg" << 'EOF'
<svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
    <rect width="512" height="512" fill="#2c3e50" rx="100"/>
    <text x="256" y="320" font-size="200" text-anchor="middle" fill="white" font-family="Arial">💬</text>
</svg>
EOF
    print_info "SVG icon created (convert to PNG for production)"
fi

# Copy any additional assets
if [ -d "mobile/assets" ]; then
    print_info "Copying additional mobile assets..."
    cp -r mobile/assets/* "$DIST_DIR/"
    print_success "Assets copied"
fi

# Create service worker for offline support
print_info "Creating service worker..."
cat > "$DIST_DIR/sw.js" << 'EOF'
// Service Worker for offline support
const CACHE_NAME = 'bedrock-chat-v1';
const urlsToCache = [
    '/',
    '/index.html',
    '/mobile-config.js',
    '/manifest.json'
];

self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => cache.addAll(urlsToCache))
    );
});

self.addEventListener('fetch', event => {
    event.respondWith(
        caches.match(event.request)
            .then(response => response || fetch(event.request))
    );
});
EOF

print_success "Service worker created"

# Summary
echo ""
echo "======================================="
echo -e "${GREEN}Mobile Build Complete!${NC}"
echo "======================================="
echo "Environment: $MOBILE_ENV"
echo "API URL: $API_URL"
echo "Output: $DIST_DIR"
echo ""
echo "Files created:"
ls -la "$DIST_DIR" | grep -E "\.(html|js|json)" | awk '{print "  - " $9}'
echo ""

# Copy the mobile HTML to the root as mobile-app.html (like fairytalegenie)
if [ -f "$DIST_DIR/index.html" ]; then
    cp "$DIST_DIR/index.html" mobile-app.html
    print_success "Mobile app copied to mobile-app.html"
else
    print_warning "Could not find processed mobile HTML file"
fi

# Check if Capacitor is configured
if [ -f "capacitor.config.json" ] || [ -f "capacitor.config.ts" ]; then
    print_info "Capacitor is configured. Run 'npx cap sync' to update native projects."
else
    print_warning "Capacitor not configured. Run 'npx cap init' to initialize."
    echo ""
    echo "Suggested command:"
    echo "  npx cap init \"$APP_NAME\" \"com.bedrockexpress.chat\" --web-dir=\"$DIST_DIR\""
fi

echo ""
print_success "Build complete!"